### ISSUE TITLE
1.5.0 stumbles over missing config.json

### ISSUE THREAD

**Issue by kay-ramme** [stanleyhlng/mocha-multi-reporters#80]
### Expected behavior
just works

### Actual behavior
crashes b/c of missing config.json

### Information about the Issue
Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at MultiReporters.getDefaultOptions (/home/ubuntu/.node_modules/lib/node_modules/@digital-coupons/buildnpm/node_modules/mocha-multi-reporters/lib/MultiReporters.js:178:40)

### Steps to reproduce the behavior

  1.  programatic mocha w/      reporter: 'mocha-multi-reporters',

**Comment by francisu** [comment]
Just released 1.5.1 which fixes this.

**Comment by kay-ramme** [comment]
checking ... :-)

**Comment by francisu** [comment]
It's embarrassing, I hit the problem right (in the product that I have that uses this) right after I released it. Obviously the tests in the package don't cover it. I will do a better job next time.

**Comment by kay-ramme** [comment]
all good, works pretty fine now, thanks for the quick fix :-)
